---
- name: Get Codec Information
  hosts: all
  gather_facts: no
  connection: local
  vars_files:
    - ~/ansible/vtc-mgmt/vault/vtc_vault.yml
  vars: 
    codec_user: admin
    codec_password: "{{ passwd }}"
    dest_file: ~/ansible/vtc-mgmt/outputs/codec-info.csv

  tasks:

    - name: Create CSV with Headers
      copy:
        content: "Codec Name, Codec Type, Codec Serial Number, Codec Software"
        dest: "{{ dest_file }}"
        force: no
      delegate_to: localhost
      run_once: yes

    - name: Get Codec Information
      uri:
        url: "https://{{ inventory_hostname }}/getxml?location=/Status/SystemUnit"  #/Software/Displayname
        method: GET 
        user: "{{ codec_user }}"
        password: "{{ codec_password }}"
        force_basic_auth: yes
        validate_certs: no 
        return_content: yes
      register: codec_info_unparsed
      delegate_to: localhost

    - name: Clean result
      set_fact:
        codec_info: "{{ codec_info_unparsed.content | ansible.utils.from_xml }}"

    - name: Display Codec Information
      debug:
        msg: 
          - "{{ codec_info.Status.SystemUnit.BroadcastName }}"  #.Status.SystemUnit.Software.DisplayName 
          - "{{ codec_info.Status.SystemUnit.ProductId }}"
          - "{{ codec_info.Status.SystemUnit.Hardware.Module.SerialNumber }}"
          - "{{ codec_info.Status.SystemUnit.Software.DisplayName }}"
        
    - name: Write to results to "{{ dest_file }}"
      lineinfile:
        path: "{{ dest_file }}"
        line: "{{ codec_info.Status.SystemUnit.BroadcastName }}, {{ codec_info.Status.SystemUnit.ProductId }}, {{ codec_info.Status.SystemUnit.Hardware.Module.SerialNumber }}, {{ codec_info.Status.SystemUnit.Software.DisplayName }}"
        create: yes
      delegate_to: localhost
